server:
  port: 8081

##### H2 in-buit in-memory database provided by Springboot configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: Admin123

  data:
    mongodb:
      uri: mongodb+srv://testuser:testuser123@cluster0.bpkqn.mongodb.net/testdata?retryWrites=true&w=majority

  view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
  thymeleaf:
    cache: false

  activemq:
    in-memory: false
    pool:
      enable: false
  active-mq-url: tcp://localhost:61616